# Generated by Django 6.0 on 2026-01-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='product_image',
        ),
    ]
