# Generated by Django 6.0 on 2026-01-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_productinfo_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='product_image',
            field=models.ImageField(default='Not Provided', upload_to='images/'),
            preserve_default=False,
        ),
    ]
