# Generated by Django 6.0 on 2026-01-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_productinfo_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='product_image',
        ),
    ]
