# Generated by Django 6.0 on 2026-01-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_productinfo_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='product_img',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='product_image',
            field=models.ImageField(default='Not Provided', upload_to='images/'),
            preserve_default=False,
        ),
    ]
